// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesApp.Infrastructure;

namespace QuotesApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190815033322_AddQuotes")]
    partial class AddQuotes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("QuotesApp.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("Date");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Source")
                        .HasMaxLength(100);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3000);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Kevin Kruse",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life is about making an impact, not making an income."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Napoleon Hill",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Whatever the mind of man can conceive and believe, it can achieve."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Albert Einstein",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Strive not to be a success, but rather to be of value."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Robert Frost",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference. "
                        },
                        new
                        {
                            Id = 5,
                            Author = "Florence Nightingale",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I attribute my success to this: I never gave or took any excuse."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Wayne Gretzky",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You miss 100% of the shots you don’t take."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Michael Jordan",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Amelia Earhart",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The most difficult thing is the decision to act, the rest is merely tenacity."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Babe Ruth",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Every strike brings me closer to the next home run."
                        },
                        new
                        {
                            Id = 10,
                            Author = "W. Clement Stone",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Definiteness of purpose is the starting point of all achievement."
                        },
                        new
                        {
                            Id = 11,
                            Author = "Kevin Kruse",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life isn't about getting and having, it's about giving and being."
                        },
                        new
                        {
                            Id = 12,
                            Author = "John Lennon",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life is what happens to you while you’re busy making other plans."
                        },
                        new
                        {
                            Id = 13,
                            Author = "Earl Nightingale",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "We become what we think about."
                        },
                        new
                        {
                            Id = 14,
                            Author = "Mark Twain",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover."
                        },
                        new
                        {
                            Id = 15,
                            Author = "Charles Swindoll",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life is 10% what happens to me and 90% of how I react to it."
                        },
                        new
                        {
                            Id = 16,
                            Author = "Alice Walker",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The most common way people give up their power is by thinking they don’t have any."
                        },
                        new
                        {
                            Id = 17,
                            Author = "Buddha",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The mind is everything. What you think you become. "
                        },
                        new
                        {
                            Id = 18,
                            Author = "Chinese Proverb",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The best time to plant a tree was 20 years ago. The second best time is now."
                        },
                        new
                        {
                            Id = 19,
                            Author = "Socrates",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "An unexamined life is not worth living."
                        },
                        new
                        {
                            Id = 20,
                            Author = "Woody Allen",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Eighty percent of success is showing up."
                        },
                        new
                        {
                            Id = 21,
                            Author = "Steve Jobs",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Your time is limited, so don’t waste it living someone else’s life."
                        },
                        new
                        {
                            Id = 22,
                            Author = "Vince Lombardi",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Winning isn’t everything, but wanting to win is."
                        },
                        new
                        {
                            Id = 23,
                            Author = "Stephen Covey",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I am not a product of my circumstances. I am a product of my decisions."
                        },
                        new
                        {
                            Id = 24,
                            Author = "Pablo Picasso",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Every child is an artist.  The problem is how to remain an artist once he grows up."
                        },
                        new
                        {
                            Id = 25,
                            Author = "Christopher Columbus",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You can never cross the ocean until you have the courage to lose sight of the shore."
                        },
                        new
                        {
                            Id = 26,
                            Author = "Maya Angelou",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel."
                        },
                        new
                        {
                            Id = 27,
                            Author = "Jim Rohn",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Either you run the day, or the day runs you."
                        },
                        new
                        {
                            Id = 28,
                            Author = "Henry Ford",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Whether you think you can or you think you can’t, you’re right."
                        },
                        new
                        {
                            Id = 29,
                            Author = "Mark Twain",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The two most important days in your life are the day you are born and the day you find out why."
                        },
                        new
                        {
                            Id = 30,
                            Author = "Johann Wolfgang von Goethe",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it."
                        },
                        new
                        {
                            Id = 31,
                            Author = "Frank Sinatra",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The best revenge is massive success."
                        },
                        new
                        {
                            Id = 32,
                            Author = "Zig Ziglar",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily."
                        },
                        new
                        {
                            Id = 33,
                            Author = "Anais Nin",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life shrinks or expands in proportion to one's courage."
                        },
                        new
                        {
                            Id = 34,
                            Author = "Vincent Van Gogh",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced."
                        },
                        new
                        {
                            Id = 35,
                            Author = "Aristotle",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "There is only one way to avoid criticism: do nothing, say nothing, and be nothing."
                        },
                        new
                        {
                            Id = 36,
                            Author = "Jesus",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you."
                        },
                        new
                        {
                            Id = 37,
                            Author = "Ralph Waldo Emerson",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The only person you are destined to become is the person you decide to be."
                        },
                        new
                        {
                            Id = 38,
                            Author = "Henry David Thoreau",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Go confidently in the direction of your dreams.  Live the life you have imagined."
                        },
                        new
                        {
                            Id = 39,
                            Author = "Erma Bombeck",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me."
                        },
                        new
                        {
                            Id = 40,
                            Author = "Booker T. Washington",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him. "
                        },
                        new
                        {
                            Id = 41,
                            Author = " Ancient Indian Proverb",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Certain things catch your eye, but pursue only those that capture the heart."
                        },
                        new
                        {
                            Id = 42,
                            Author = "Theodore Roosevelt",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Believe you can and you’re halfway there."
                        },
                        new
                        {
                            Id = 43,
                            Author = "George Addair",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Everything you’ve ever wanted is on the other side of fear."
                        },
                        new
                        {
                            Id = 44,
                            Author = "Plato",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light."
                        },
                        new
                        {
                            Id = 45,
                            Author = "Maimonides",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Teach thy tongue to say, \"I do not know,\" and thous shalt progress."
                        },
                        new
                        {
                            Id = 46,
                            Author = "Arthur Ashe",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Start where you are. Use what you have. Do what you can."
                        },
                        new
                        {
                            Id = 47,
                            Author = "John Lennon",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up.I wrote down 'happy'. They told me I didn’t understand the assignment, and I told them they didn’t understande life."
                        },
                        new
                        {
                            Id = 48,
                            Author = "Japanese Proverb",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Fall seven times and stand up eight."
                        },
                        new
                        {
                            Id = 49,
                            Author = "Helen Keller",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us."
                        },
                        new
                        {
                            Id = 50,
                            Author = "Confucius",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Everything has beauty, but not everyone can see."
                        },
                        new
                        {
                            Id = 51,
                            Author = "Anne Frank",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "How wonderful it is that nobody need wait a single moment before starting to improve the world."
                        },
                        new
                        {
                            Id = 52,
                            Author = "Lao Tzu",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "When I let go of what I am, I become what I might be."
                        },
                        new
                        {
                            Id = 53,
                            Author = "Maya Angelou",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life is not measured by the number of breaths we take, but by the moments that take our breath away."
                        },
                        new
                        {
                            Id = 54,
                            Author = "Dalai Lama",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Happiness is not something readymade.  It comes from your own actions."
                        },
                        new
                        {
                            Id = 55,
                            Author = "Sheryl Sandberg",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If you're offered a seat on a rocket ship, don't ask what seat! Just get on."
                        },
                        new
                        {
                            Id = 56,
                            Author = "Aristotle",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end."
                        },
                        new
                        {
                            Id = 57,
                            Author = "Latin Proverb",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If the wind will not serve, take to the oars."
                        },
                        new
                        {
                            Id = 58,
                            Author = "Unknown",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground."
                        },
                        new
                        {
                            Id = 59,
                            Author = "Marie Curie",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained."
                        },
                        new
                        {
                            Id = 60,
                            Author = "Les Brown",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Too many of us are not living our dreams because we are living our fears."
                        },
                        new
                        {
                            Id = 61,
                            Author = "Joshua J. Marine",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Challenges are what make life interesting and overcoming them is what makes life meaningful."
                        },
                        new
                        {
                            Id = 62,
                            Author = "Booker T. Washington",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If you want to lift yourself up, lift up someone else."
                        },
                        new
                        {
                            Id = 63,
                            Author = "Leonardo da Vinci",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do."
                        },
                        new
                        {
                            Id = 64,
                            Author = "Jamie Paolinetti",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless."
                        },
                        new
                        {
                            Id = 65,
                            Author = "Erica Jong",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You take your life in your own hands, and what happens? A terrible thing, no one to blame."
                        },
                        new
                        {
                            Id = 66,
                            Author = "Bob Dylan",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do."
                        },
                        new
                        {
                            Id = 67,
                            Author = "Benjamin Franklin",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I didn’t fail the test. I just found 100 ways to do it wrong."
                        },
                        new
                        {
                            Id = 68,
                            Author = "Bill Cosby",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "In order to succeed, your desire for success should be greater than your fear of failure."
                        },
                        new
                        {
                            Id = 69,
                            Author = " Albert Einstein",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "A person who never made a mistake never tried anything new."
                        },
                        new
                        {
                            Id = 70,
                            Author = "Chinese Proverb",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The person who says it cannot be done should not interrupt the person who is doing it."
                        },
                        new
                        {
                            Id = 71,
                            Author = "Roger Staubach",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "There are no traffic jams along the extra mile."
                        },
                        new
                        {
                            Id = 72,
                            Author = "George Eliot",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "It is never too late to be what you might have been."
                        },
                        new
                        {
                            Id = 73,
                            Author = "Oprah Winfrey",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You become what you believe."
                        },
                        new
                        {
                            Id = 74,
                            Author = "Vincent van Gogh",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I would rather die of passion than of boredom."
                        },
                        new
                        {
                            Id = 75,
                            Author = "Unknown",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "A truly rich man is one whose children run into his arms when his hands are empty."
                        },
                        new
                        {
                            Id = 76,
                            Author = "Ann Landers",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings. "
                        },
                        new
                        {
                            Id = 77,
                            Author = "Abigail Van Buren",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If you want your children to turn out well, spend twice as much time with them, and half as much money."
                        },
                        new
                        {
                            Id = 78,
                            Author = "Farrah Gray",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Build your own dreams, or someone else will hire you to build theirs."
                        },
                        new
                        {
                            Id = 79,
                            Author = "Jesse Owens",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The battles that count aren't the ones for gold medals. The struggles within yourself-the invisible battles inside all of us-that's where it's at."
                        },
                        new
                        {
                            Id = 80,
                            Author = "Sir Claus Moser",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Education costs money.  But then so does ignorance."
                        },
                        new
                        {
                            Id = 81,
                            Author = "Rosa Parks",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "I have learned over the years that when one's mind is made up, this diminishes fear."
                        },
                        new
                        {
                            Id = 82,
                            Author = "Confucius",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "It does not matter how slowly you go as long as you do not stop."
                        },
                        new
                        {
                            Id = 83,
                            Author = "Oprah Winfrey",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough."
                        },
                        new
                        {
                            Id = 84,
                            Author = "Dalai Lama",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Remember that not getting what you want is sometimes a wonderful stroke of luck."
                        },
                        new
                        {
                            Id = 85,
                            Author = "Maya Angelou",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You can’t use up creativity.  The more you use, the more you have."
                        },
                        new
                        {
                            Id = 86,
                            Author = "Norman Vaughan",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Dream big and dare to fail."
                        },
                        new
                        {
                            Id = 87,
                            Author = "Martin Luther King Jr.",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Our lives begin to end the day we become silent about things that matter."
                        },
                        new
                        {
                            Id = 88,
                            Author = "Teddy Roosevelt",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Do what you can, where you are, with what you have."
                        },
                        new
                        {
                            Id = 89,
                            Author = "Tony Robbins",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "If you do what you’ve always done, you’ll get what you’ve always gotten."
                        },
                        new
                        {
                            Id = 90,
                            Author = "Gloria Steinem",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Dreaming, after all, is a form of planning."
                        },
                        new
                        {
                            Id = 91,
                            Author = "Mae Jemison",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live."
                        },
                        new
                        {
                            Id = 92,
                            Author = "Beverly Sills",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "You may be disappointed if you fail, but you are doomed if you don't try."
                        },
                        new
                        {
                            Id = 93,
                            Author = "Eleanor Roosevelt",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Remember no one can make you feel inferior without your consent."
                        },
                        new
                        {
                            Id = 94,
                            Author = "Grandma Moses",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Life is what we make it, always has been, always will be."
                        },
                        new
                        {
                            Id = 95,
                            Author = "Ayn Rand",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "The question isn’t who is going to let me; it’s who is going to stop me."
                        },
                        new
                        {
                            Id = 96,
                            Author = "Henry Ford",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it."
                        },
                        new
                        {
                            Id = 97,
                            Author = "Abraham Lincoln",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "It’s not the years in your life that count. It’s the life in your years."
                        },
                        new
                        {
                            Id = 98,
                            Author = "Norman Vincent Peale",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Change your thoughts and you change your world."
                        },
                        new
                        {
                            Id = 99,
                            Author = "Benjamin Franklin",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = "Either write something worth reading or do something worth writing."
                        },
                        new
                        {
                            Id = 100,
                            Author = "Audrey Hepburn",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = ". Nothing is impossible, the word itself says, “I’m possible!”"
                        },
                        new
                        {
                            Id = 101,
                            Author = "Steve Jobs",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = ". The only way to do great work is to love what you do."
                        },
                        new
                        {
                            Id = 102,
                            Author = "Zig Ziglar",
                            CreatedAt = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            Text = ". If you can dream it, you can achieve it."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
